In [1]:
%load_ext autoreload
%autoreload 2

import time
import pysbrl
import numpy as np
from imodels import BayesianRuleListClassifier
from imodels.util.discretization.simple import SimpleDiscretizer
from imodels.util.rule import get_feature_dict
from experiments.util import get_clean_dataset

In [146]:
X, y, fnames = get_clean_dataset("../data/credit_g.csv")

In [147]:
feature_dict_ = get_feature_dict(X.shape[1], fnames)
feature_placeholders = np.array(list(feature_dict_.keys()))
feature_names = np.array(list(feature_dict_.values()))

disc = SimpleDiscretizer(n_bins=4, strategy='quantile')
disc.fit(X, feature_placeholders)
X_disc = disc.transform(X)

/accounts/projects/binyu/keyan3/miniconda3/envs/imodels-3.9/lib/python3.9/site-packages/sklearn/preprocessing/_discretization.py:220: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn('Bins whose width are too small (i.e., <= '
/accounts/projects/binyu/keyan3/miniconda3/envs/imodels-3.9/lib/python3.9/site-packages/sklearn/preprocessing/_discretization.py:220: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn('Bins whose width are too small (i.e., <= '
/accounts/projects/binyu/keyan3/miniconda3/envs/imodels-3.9/lib/python3.9/site-packages/sklearn/preprocessing/_discretization.py:220: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn('Bins whose width are too small (i.e., <= '


In [148]:
X_disc

feature_0_-inf_to_12.0  feature_0_12.0_to_18.0  feature_0_18.0_to_24.0  \
0                       1.0                     0.0                     0.0   
1                       0.0                     0.0                     0.0   
2                       0.0                     1.0                     0.0   
3                       0.0                     0.0                     0.0   
4                       0.0                     0.0                     0.0   
..                      ...                     ...                     ...   
995                     0.0                     1.0                     0.0   
996                     0.0                     0.0                     0.0   
997                     0.0                     1.0                     0.0   
998                     0.0                     0.0                     0.0   
999                     0.0                     0.0                     0.0   

     feature_0_24.0_to_inf  feature_1_-inf_to_1365.5  \
0                      0.0                       1.0   
1                      1.0                       0.0   
2                      0.0                       0.0   
3                      1.0                       0.0   
4                      1.0                       0.0   
..                     ...                       ...   
995                    0.0                       0.0   
996                    1.0                       0.0   
997                    0.0                       1.0   
998                    1.0                       0.0   
999                    1.0                       0.0   

     feature_1_1365.5_to_2319.5  feature_1_2319.5_to_3972.25  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           1.0                          0.0   
3                           0.0                          0.0   
4                           0.0                          0.0   
..                          ...                          ...   
995                         1.0                          0.0   
996                         0.0                          1.0   
997                         0.0                          0.0   
998                         1.0                          0.0   
999                         0.0                          0.0   

     feature_1_3972.25_to_inf  feature_2_-inf_to_2.0  feature_2_2.0_to_3.0  \
0                         0.0                    0.0                   0.0   
1                         1.0                    0.0                   1.0   
2                         0.0                    0.0                   1.0   
3                         1.0                    0.0                   1.0   
4                         1.0                    0.0                   0.0   
..                        ...                    ...                   ...   
995                       0.0                    0.0                   0.0   
996                       0.0                    0.0                   0.0   
997                       0.0                    0.0                   0.0   
998                       0.0                    0.0                   0.0   
999                       1.0                    0.0                   0.0   

     ...  feature_50  feature_51  feature_52  feature_53  feature_54  \
0    ...         1.0         0.0         1.0         0.0         0.0   
1    ...         1.0         0.0         1.0         0.0         0.0   
2    ...         1.0         0.0         1.0         0.0         0.0   
3    ...         1.0         0.0         0.0         1.0         0.0   
4    ...         1.0         0.0         0.0         1.0         0.0   
..   ...         ...         ...         ...         ...         ...   
995  ...         1.0         0.0         1.0         0.0         0.0   
996  ...         1.0         0.0         1.0         0.0         0.0   
997  ...         1.0         

In [122]:
disc.discretizer.bin_edges_

array([array([ 4., 12., 18., 24., 72.]),
       array([  250.  ,  1365.5 ,  2319.5 ,  3972.25, 18424.  ]),
       array([1., 2., 3., 4.]), array([1., 2., 3., 4.]),
       array([19., 27., 33., 42., 75.]), array([1., 2., 4.])],
      dtype=object)

In [145]:
((X[:, 1] > 1365.5) & (X[:, 1] <= 2319.5)).astype(int).sum()

250

In [137]:
X[:, 0]

array([ 6., 48., 12., 42., 24., 36., 24., 36., 12., 30., 12., 48., 12.,
       24., 15., 24., 24., 30., 24., 24.,  9.,  6., 10., 12., 10.,  6.,
        6., 12.,  7., 60., 18., 24., 18., 12., 12., 45., 48., 18., 10.,
        9., 30., 12., 18., 30., 48., 11., 36.,  6., 11., 12., 24., 27.,
       12., 18., 36.,  6., 12., 36., 18., 36.,  9., 15., 36., 48., 24.,
       27., 12., 12., 36., 36., 36.,  7.,  8., 42., 36., 12., 42., 11.,
       54., 30., 24., 15., 18., 24., 10., 12., 18., 36., 18., 12., 12.,
       12., 12., 24., 12., 54., 12., 18., 36., 20., 24., 36.,  6.,  9.,
       12., 24., 18., 12., 24., 14.,  6., 15., 18., 36., 12., 48., 42.,
       10., 33., 12., 21., 24., 12., 10., 18., 12., 12., 12., 12., 12.,
       48., 36., 15., 18., 60., 12., 27., 12., 15., 12.,  6., 36., 27.,
       18., 21., 48.,  6., 12., 36., 18.,  6., 10., 36., 24., 24., 12.,
        9., 12., 24.,  6., 24., 18., 15., 10., 36.,  6., 18., 11., 24.,
       24., 15., 12., 24.,  8., 21., 30., 12.,  6., 12., 21., 36

In [81]:
X_disc.iloc[:, 16].value_counts()

0.0    667
1.0    333
Name: feature_5_2.0_to_3.0, dtype: int64

In [18]:
disc.is_categorical

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [19]:
X_disc

feature_0_4.0_to_12.5  feature_0_12.5_to_21.0  feature_0_21.0_to_29.5  \
0                      1.0                     0.0                     0.0   
1                      0.0                     0.0                     0.0   
2                      1.0                     0.0                     0.0   
3                      0.0                     0.0                     0.0   
4                      0.0                     0.0                     1.0   
..                     ...                     ...                     ...   
995                    1.0                     0.0                     0.0   
996                    0.0                     0.0                     0.0   
997                    1.0                     0.0                     0.0   
998                    0.0                     0.0                     0.0   
999                    0.0                     0.0                     0.0   

     feature_0_29.5_to_38.0  feature_0_38.0_to_46.5  feature_0_46.5_to_55.0  \
0                       0.0                     0.0                     0.0   
1                       0.0                     0.0                     1.0   
2                       0.0                     0.0                     0.0   
3                       0.0                     1.0                     0.0   
4                       0.0                     0.0                     0.0   
..                      ...                     ...                     ...   
995                     0.0                     0.0                     0.0   
996                     1.0                     0.0                     0.0   
997                     0.0                     0.0                     0.0   
998                     0.0                     1.0                     0.0   
999                     0.0                     1.0                     0.0   

     feature_0_55.0_to_63.5  feature_0_63.5_to_72.0  \
0                       0.0                     0.0   
1                       0.0                     0.0   
2                       0.0                     0.0   
3                       0.0                     0.0   
4                       0.0                     0.0   
..                      ...                     ...   
995                     0.0                     0.0   
996                     0.0                     0.0   
997                     0.0                     0.0   
998                     0.0                     0.0   
999                     0.0                     0.0   

     feature_1_250.0_to_2521.75  feature_1_2521.75_to_4793.5  ...  feature_50  \
0                           1.0                          0.0  ...         1.0   
1                           0.0                          0.0  ...         1.0   
2                           1.0                          0.0  ...         1.0   
3                           0.0                          0.0  ...         1.0   
4                           0.0                          0.0  ...         1.0   
..                          ...                          ...  ...         ...   
995                         1.0                          0.0  ...         1.0   
996                         0.0                          1.0  ...         1.0   
997                         1.0                          0.0  ...         1.0   
998                         1.0                          0.0  ...         1.0   
999                         0.0                          1.0  ...         1.0   

     feature_51  feature_52  feature_53  feature_54  feature_55  feature_56  \
0           0.0         1.0         0.0         0.0         0.0         1.0   
1           0.0         1.0         0.0         0.0         0.0         1.0   
2           0.0         1.0         0.0         0.0         1.0         0.0   
3           0.0         0.0         1.0         0.0         0.0         1.0   
4           0.0         0.0         1.0         0.0         0.0         1.0   
..         

In [149]:
freq = pysbrl.utils.categorical2pysbrl_data(
    X_disc.values.astype(int), 
    y.astype(int),
    data_filename='credit_sbrl.data', 
    label_filename='credit_sbrl.label',
    supp=0.5)

[('x64=1', 'x66=1', 'x72=1'), ('x55=1',), ('x41=1', 'x55=1', 'x72=1'), ('x10=1',), ('x10=1', 'x72=1')]
[[[64, 66, 72], [1, 1, 1]], [[55], [1]], [[41, 55, 72], [1, 1, 1]], [[10], [1]], [[10, 72], [1, 1]]]


In [151]:
((X_disc.iloc[:, 64] == 1) & (X_disc.iloc[:, 66] == 1) & (X_disc.iloc[:, 72] == 1)).value_counts()

False    503
True     497
dtype: int64

In [79]:
X_disc.iloc[:, 15]

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ... 
995    1.0
996    1.0
997    1.0
998    1.0
999    1.0
Name: feature_5_1.0_to_2.0, Length: 1000, dtype: float32

In [26]:
start = time.time()
# pysbrl.utils.categorical2pysbrl_data(
#     X_disc.values.astype(int), 
#     y.astype(int), 
#     data_filename='hab_sbrl.data', 
#     label_filename='hab_sbrl.label',
#     supp=0.1)
rule_ids, outputs, rule_strings = pysbrl.train_sbrl('credit_sbrl.data', 'credit_sbrl.label', 
                                                    max_iters=100000, lambda_=5, eta=3)
end = time.time()

In [27]:
rules = [rule_strings[i] for i in rule_ids]
rules

['{x100=1,x69=1,x83=1}', '{x92=1,x94=1}', '{x100=1,x40=1,x83=1}', 'default']

In [28]:
is_ind = [[int(t.split('x')[-1].split('=')[0]) for t in rule_string.split(',')] for rule_string in rules[:-1]]

In [29]:
X_disc.columns.values[is_ind[1]].tolist()

['feature_50', 'feature_52']

In [30]:
from imodels.util.convert import itemsets_to_rules

In [31]:
final_rules = itemsets_to_rules([X_disc.columns.values[inds].tolist() for inds in is_ind])

In [42]:
final_rules[2]

'feature_58 > 0.5 and feature_5 > 1.0 and feature_5 <= 1.375 and feature_41 > 0.5'

In [36]:
import pandas as pd

In [51]:
pd.DataFrame(X, columns=feature_placeholders).query(
    'feature_5 <= 1.375'
)

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
1         48.0     5951.0        2.0        2.0       22.0        1.0   
2         12.0     2096.0        2.0        3.0       49.0        1.0   
3         42.0     7882.0        2.0        4.0       45.0        1.0   
5         36.0     9055.0        2.0        4.0       35.0        1.0   
6         24.0     2835.0        3.0        4.0       53.0        1.0   
..         ...        ...        ...        ...        ...        ...   
995       12.0     1736.0        3.0        4.0       31.0        1.0   
996       30.0     3857.0        4.0        4.0       40.0        1.0   
997       12.0      804.0        4.0        4.0       38.0        1.0   
998       45.0     1845.0        4.0        4.0       23.0        1.0   
999       45.0     4576.0        3.0        4.0       27.0        1.0   

     feature_6  feature_7  feature_8  feature_9  ...  feature_50  feature_51  \
1          0.0        0.0        0.0        1.0  ...         1.0         0.0   
2          0.0        0.0        0.0        0.0  ...         1.0         0.0   
3          0.0        0.0        1.0        0.0  ...         1.0         0.0   
5          1.0        0.0        0.0        0.0  ...         1.0         0.0   
6          0.0        0.0        0.0        0.0  ...         1.0         0.0   
..         ...        ...        ...        ...  ...         ...         ...   
995        0.0        0.0        0.0        0.0  ...         1.0         0.0   
996        1.0        0.0        1.0        0.0  ...         1.0         0.0   
997        0.0        0.0        0.0        0.0  ...         1.0         0.0   
998        1.0        0.0        1.0        0.0  ...         1.0         0.0   
999        0.0        0.0        0.0        1.0  ...         1.0         0.0   

     feature_52  feature_53  feature_54  feature_55  feature_56  feature_57  \
1           1.0         0.0         0.0         0.0         1.0         0.0   
2           1.0         0.0         0.0         1.0         0.0         0.0   
3           0.0         1.0         0.0         0.0         1.0         0.0   
5           0.0         1.0         0.0         1.0         0.0         0.0   
6           1.0         0.0         0.0         0.0         1.0         0.0   
..          ...         ...         ...         ...         ...         ...   
995         1.0         0.0         0.0         1.0         0.0         0.0   
996         1.0         0.0         0.0         0.0         0.0         1.0   
997         1.0         0.0         0.0         0.0         1.0         0.0   
998         0.0         1.0         0.0         0.0         1.0         0.0   
999         1.0         0.0         0.0         0.0         1.0         0.0   

     feature_58  feature_59  
1           1.0         0.0  
2           0.0         1.0  
3           0.0         1.0  
5           0.0         1.0  
6           1.0         0.0  
..          ...         ...  
995         1.0         0.0  
996         1.0         0.0  
997         1.0         0.0  
998         1.0         0.0  
999         1.0         0.0  

[633 rows x 60 columns]

In [54]:
pd.DataFrame(X, columns=feature_placeholders)['feature_5'].value_counts()

1.0    633
2.0    333
3.0     28
4.0      6
Name: feature_5, dtype: int64

In [159]:
X.query(final_rules[1])

AttributeError: 'numpy.ndarray' object has no attribute 'query'

In [105]:
outputs

array([[0.08433735, 0.91566265],
       [0.5645933 , 0.4354067 ],
       [0.33763441, 0.66236559]])

In [74]:
X_disc.columns[1]

'duration_12.5_to_21.0'

In [88]:
end - start

5.031540632247925

In [106]:
start_ = time.time()
m = BayesianRuleListClassifier(max_iter=30000, disc_strategy='simple', maxcardinality=3)
m.fit(X, y, fnames)
end_ = time.time()

      support      itemsets
0       0.907          (83)
1       0.845         (100)
2       0.814          (92)
3       0.713          (94)
4       0.630          (98)
...       ...           ...
1835    0.122   (1, 83, 94)
1836    0.121  (1, 100, 94)
1837    0.105   (1, 92, 94)
1838    0.120      (90, 83)
1839    0.108     (90, 100)

[1840 rows x 2 columns]
[(83,), (100,), (92,), (94,), (98,), (81,), (8,), (23,), (31,), (48,), (0,), (42,), (58,), (86,), (62,), (50,), (78,), (73,), (40,), (69,), (56,), (76,), (80,), (26,), (51,), (18,), (32,), (53,), (97,), (77,), (101,), (29,), (87,), (61,), (35,), (95,), (59,), (2,), (21,), (89,), (34,), (3,), (9,), (88,), (93,), (99,), (60,), (33,), (75,), (24,), (16,), (1,), (70,), (90,), (83, 100), (83, 92), (100, 92), (100, 83, 92), (83, 94), (100, 94), (92, 94), (83, 100, 94), (83, 92, 94), (100, 92, 94), (98, 83), (98, 100), (98, 92), (98, 94), (40, 98), (98, 83, 100), (98, 83, 92), (100, 98, 92), (98, 83, 94), (98, 100, 94), (98, 92, 94), (40,

In [83]:
end_ - start_

13.260505199432373

In [107]:
m

Trained RuleListClassifier 
IF checking_status_3.0 > 0.5 and other_payment_plans_2.0 > 0.5 THEN probability of class 1: 91.6% (88.4%-94.3%)
ELSE IF duration <= 12.5 and duration > 4.0 and property_magnitude_0.0 > 0.5 THEN probability of class 1: 81.0% (72.8%-88.0%)
ELSE IF credit_history_4.0 > 0.5 and job_2.0 > 0.5 and other_payment_plans_2.0 > 0.5 THEN probability of class 1: 75.4% (64.3%-85.0%)
ELSE IF purpose_0.0 > 0.5 THEN probability of class 1: 36.2% (27.7%-45.1%)
ELSE IF checking_status_1.0 > 0.5 THEN probability of class 1: 57.7% (49.9%-65.3%)
ELSE IF job_3.0 > 0.5 THEN probability of class 1: 69.8% (55.4%-82.4%)
ELSE IF checking_status_0.0 > 0.5 and other_parties_0.0 > 0.5 and savings_status_0.0 > 0.5 THEN probability of class 1: 29.9% (20.8%-39.9%)
ELSE probability of class 1: 73.5% (65.2%-81.1%)
